version: '3.9'

services:
  # dgraph_zero:
  #   image: dgraph/dgraph:latest
  #   container_name: dgraph_zero
  #   ports:
  #     # - '5080:5080'
  #     - '6080:6080'
  #   environment:
  #     DGRAPH_ZERO_MY: http://dgraph_zero:5080
  #   volumes:
  #     - dgraph_zero:/dgraph:rw
  #   restart: on-failure
  #   command: dgraph zero
  #   healthcheck:
  #     test: curl http://dgraph_zero:6080/state || exit 1
  #     interval: 10s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 15s

  # dgraph_alpha:
  #   image: dgraph/dgraph:latest
  #   container_name: dgraph_alpha
  #   depends_on:
  #     dgraph_zero:
  #       condition: service_healthy
  #   ports:
  #     # - '7080:7080'
  #     - '8080:8080'
  #     # - '9080:9080'
  #   environment:
  #     DGRAPH_ALPHA_GRAPHQL: "lambda-url=http://dgraph_lambda:8686/graphql-worker"
  #     DGRAPH_ALPHA_ZERO: http://dgraph_zero:5080
  #     DGRAPH_ALPHA_MY: http://dgraph_alpha:7080
  #   volumes:
  #     - dgraph_alpha:/dgraph:rw
  #   restart: on-failure
  #   command: dgraph alpha
  #   healthcheck:
  #     test: curl http://dgraph_alpha:8080/health || exit 1
  #     interval: 10s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 15s

  dgraph:
    image: dgraph/standalone:v21.03.2
    container_name: dgraph
    ports:
      # - '5080:5080'
      - '6080:6080'
      # - '7080:7080'
      - '8080:8080'
      # - '9080:9080'
      - '8000:8000'
    environment:
      DGRAPH_ALPHA_GRAPHQL: "lambda-url=http://dgraph_lambda:8686/graphql-worker" # dgraph lambda endpoint
    volumes:
      - dgraph:/dgraph:rw
    # restart: on-failure
    healthcheck:
      test: curl http://dgraph:8080/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 15s

  dgraph_lambda:
    image: dgraph/dgraph-lambda:latest
    container_name: dgraph_lambda
    depends_on:
      dgraph:
        condition: service_healthy
    ports:
      - '8686:8686'
    environment:
      DGRAPH_URL: http://dgraph:8080 # dgraph alpha endpoint
    volumes:
      - ./dist:/app/script:ro
    restart: on-failure

volumes:
  # dgraph_zero: {}
  # dgraph_alpha: {}
  dgraph: {}
  lambda_script: {}
